---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: cis-admin
rules:
  - apiGroups:
      - cis.cattle.io
    resources:
      - clusterscanbenchmarks
      - clusterscanprofiles
      - clusterscans
      - clusterscanreports
    verbs: ["create", "update", "delete", "patch","get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: cis-edit
rules:
  - apiGroups:
      - cis.cattle.io
    resources:
      - clusterscanbenchmarks
      - clusterscanprofiles
      - clusterscans
      - clusterscanreports
    verbs: ["create", "update", "delete", "patch","get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: cis-view
rules:
  - apiGroups:
      - cis.cattle.io
    resources:
      - clusterscanbenchmarks
      - clusterscanprofiles
      - clusterscans
      - clusterscanreports
    verbs: ["get", "watch", "list"]