apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: rancher-logging
spec:
  fluentbit:
    resources:
      requests:
        cpu: 100m    
  fluentd:
    resources:
      requests:
        cpu: 100m
